### ISSUE TITLE
Feature Request: Emby Compatibility

### ISSUE THREAD

**Issue by hacshacdgacs** [Schaka/janitorr#16]
Basically the header, I know Jellyfin was a fork off of Emby but that doesn't mean it'll be plug and play.

**Comment by hacshacdgacs** [comment]
Have just set it up and it doesn't seem like it does. Consider this a featrue request for Emby please as this does look like a very useful tool. Thanks

**Comment by Schaka** [comment]
No promises. It's not really within the scope of this application and you can absolutely use it without Jellyfin.
Jellyseerr can be used with Emby. Media is deleted through the *arrs and requests will be deleted via Jellyseerr.

Setting up Emby and learning how to handle collections will probably take some time.
I assume all of this *should* be possible in the free version? I definitely don't want to pay for a license.

I already will have to pay the license fee for IntelliJ, if JetBrains doesn't supply me with an open-source license.

**Comment by hacshacdgacs** [comment]
Fair enough, could you help me with the setup of the application file? Everything as far as I'm aware should be working but the application is failing to start. Thanks  (uploading as a txt so github can read it but original is a yaml)
[application.txt](https://github.com/Schaka/janitorr/files/14515280/application.txt)

[_Janitorr_logs.txt](https://github.com/Schaka/janitorr/files/14515281/_Janitorr_logs.txt)

**Comment by Schaka** [comment]
There seems to be some bug still. Remove "exclusion-tag" entirely for now. It'll be fixed on a develop build in a few hours.

**Comment by hacshacdgacs** [comment]
After removing that I seem to get a new error tied into I assume sonarr
[_Janitorr_logs(1).txt](https://github.com/Schaka/janitorr/files/14515418/_Janitorr_logs.1.txt)

**Comment by Schaka** [comment]
If you aren't on Sonarr v4, it's not tested and I unfortunately can't make compatibility changes. 
If this happened on Sonarr v4, you may have found an inconsitency that hasn't happened to any of the other users and I should be able to adjust structure.

I recommend you switch to the develop build.

**Comment by hacshacdgacs** [comment]
I am on sonarr v4, I'll swap to the develop build and see if that fixes anything

**Comment by hacshacdgacs** [comment]
Develop build works fine

**Comment by Schaka** [comment]
Great. Please let me know if Emby's leaving soon collection works on the latest develop build.
I'm in the process of setting up a test environment to see how different Emby and Jellyfin are. Things might be easier than I had originally thought.

**Comment by hacshacdgacs** [comment]
It doesn't appear to do so 
[_Janitorr_logs(4).txt](https://github.com/Schaka/janitorr/files/14516150/_Janitorr_logs.4.txt)
I do have media split over two drives (TV on one Movies on the other) but this is with it failing with only one set up currently

**Comment by Schaka** [comment]
I'm surprised you came that far. You used the Jellyfin config, not Emby, by the looks of it.
It shouldn't even have been able to log in at that point. 

I corrected the error (at least roughly) seen in your last log entry. However, I split Jellyfin and Emby on purpose and have only implemented Leaving Soon into Emby so far.

**Comment by hacshacdgacs** [comment]
I can see how that'd be an issue. So do I swap out jellyfin: for emby: and that should fix that config?

**Comment by hacshacdgacs** [comment]
[_Janitorr_logs.txt](https://github.com/Schaka/janitorr/files/14516454/_Janitorr_logs.txt)
[application.txt](https://github.com/Schaka/janitorr/files/14516476/application.txt)
I appreciate the effort you're putting in tryign to get this to work btw. I've attached my config and latest log

**Comment by hacshacdgacs** [comment]
[_Janitorr_logs(1).txt](https://github.com/Schaka/janitorr/files/14519697/_Janitorr_logs.1.txt)
So it's connected to Emby but now it's trying to append /tv to the end of the leaving soon dir I gave it so it's unable to find a folder

**Comment by Schaka** [comment]
Please grab the latest develop build in 2 minutes from this post.
It removed the initial '/' from your path (which is what the problem was). It appending movies/tv is correct.

This happened, because I tried to maintain Windows compatibility.

**Comment by hacshacdgacs** [comment]
[_Janitorr_logs.txt](https://github.com/Schaka/janitorr/files/14519907/_Janitorr_logs.txt)
Latest error. the folders are busy?

**Comment by Schaka** [comment]
I have no idea what that means. I suspect this may be a network mount or Janitorr can't write to it. 
Apparently it can happen if some files are currently open.

**Comment by hacshacdgacs** [comment]
It's a drive hosted on the machine and their shouldn't be anything in the files in the folders as I just created them for Janitorr now. I've given everything permission to wruite and read from it also so yea. I'm not sure about it either

**Comment by Schaka** [comment]
You may have the drive/folder open in some editor.
All Janitorr does is create a subfolder in your leaving-soon directory called movies and tv.

You may create those folders yourself and make sure they have the correct permissions.

**Comment by hacshacdgacs** [comment]
So Janitorr makes the library for the Shows (Deleted Soon) and then throws up that error. I'll try a restart of the whole system and see if that fixes things somehow

**Comment by Schaka** [comment]
The code between Jellyfin and Emby for creation of actual symlinks (i.e. what makes the media appear in the new libraries) is identical. It is purely based on filesystem access. While I don't have a library where I can test this for Emby without putting in quite a bit more effort - this exact code (i.e. filesystem access) works for Jellyfin on 3 systems I've tested it on.

**Comment by Schaka** [comment]
Currently, that's not possible. You'd have to wait until I implement the ability to disable Sonarr or Radarr.

**Comment by Schaka** [comment]
You can now disable Sonarr/Radarr on the latest develop build.

**Comment by hacshacdgacs** [comment]
I think I managed to get it to work. My disk or drive busy error was caused by me mapping the /tv and /movie folders in docker also. (Not sure why I did that, brain fade on my end) Removing that and everything seems to work fine now. 

I noticed that even though i have it starting with sonarr disabled it still creates a Shows (Deleted Soon) folder. Is that intentional?

**Comment by Schaka** [comment]
Yes, that's intentional. If Jellyfin/Emby is enabled, they take care of creating collections independently. I could make it reject empty collections altogether - it wouldn't create a new collection then but still keep olds ones etc.

I may add that in for easier usability.

**Comment by hacshacdgacs** [comment]
That may look nicer from a Media Server perspective cause in my use case now it will have an always empty shows folder. With this current build is the leaving soon collection meant to be populating?
Currently I'm getting the following error. (Docker is mapped to see /mnt/sdc2/Movies as a path so it should be able to find all the movies)


2024-03-08T03:37:28.070Z TRACE 1 --- [   scheduling-1] c.g.s.j.mediaserver.MediaServerService   : Movie folder - PathStructure(sourceFolder=/mnt/sdc2/Movies/No Sudden Move (2021), sourceFile=/mnt/sdc2/Movies/No Sudden Move (2021)/No Sudden Move (2021) .mkv, targetFolder=/mnt/sdc2/Leaving Soon/movies/No Sudden Move (2021), targetFile=/mnt/sdc2/Leaving Soon/movies/No Sudden Move (2021)/No Sudden Move (2021) .mkv)

2024-03-08T03:37:28.072Z  INFO 1 --- [   scheduling-1] c.g.s.j.mediaserver.MediaServerService   : Can't find original movie folder - no links to create /mnt/sdc2/Movies/No Sudden Move (2021)/No Sudden Move (2021) .mkv

**Comment by Schaka** [comment]
From the readme:

> "Leaving Soon" Collections are always created and do not care for dry-run settings

If it can't find those movies, they likely don't exist under that name. You either didn't mount the folders correctly or the files were renamed later on. Janitorr reads the original filename as well as the renamed filename from Sonarr/Radarr's history.

I am noticing a space before the file extension for your movie file. Janitorr does not create those spaces.

**Comment by hacshacdgacs** [comment]
Okay, cross-seed has no issues with the exact same mounting path in docker. I've redone the radarr naming scheme and that still fails to find the folder. I guess I'll have a look into mergerfs

**Comment by Schaka** [comment]
Hop into the container via `docker  run -it container-name /bin/sh`. See if the mapping exists.
If the path /mnt/sdc2/* doesn't exist inside the container (and I would assume it does not), then it can't find the files.
If you CAN find it when you're searching for the file manually, we can investigate further.

It may or may not be that space in the filename. It's not created by Janitorr, this is covered by unit tests.

**Comment by hacshacdgacs** [comment]
I've renamed it so that the space isn't there and it still wasn't able to pick it up. It doesn't seem to be able to find it in docker so there must be something wrong with my pathing currently. I'll try sort it out then try again later.

**Comment by hacshacdgacs** [comment]
Sorry, is it possible for you to screnshot your current pathing in docker? I feel like this should work and it's still not wanting to. It's able to set up the Leaving Soon library in Emby with only this pathing but is refusing to find the movies. 
![image](https://github.com/Schaka/janitorr/assets/85550264/07ddff6b-5954-43c6-8227-b9da226d339d)

**Comment by Schaka** [comment]
```
services:
  janitorr:
    container_name: janitorr
    image: schaka/janitorr:develop
    ports:
      - 8978:8978 # Technically, we don't publish any endpoints, so this isn't strictly required
    volumes:
      - /appdata/janitorr/config:/config
      - /share_media:/data
      
    networks:
      - htpc  
    restart: unless-stopped
```
This is my entire config.

Sonarr/Radarr are the same. Radarr has its media library at `/data/media/movies` and Sonarr at `/data/media/tv`.
Jellyfin knows both of these and finds them under `/data/media/movies/`.
Janitorr writes to `/data/media/leaving-soon/movies`. 

They all have the exact same mapping. As of now, I really don't have any plans to allow for any sort of settings to rewrite paths. It's going to complicate things vastly and won't solve any issues with people's weird configs or drives.

If you use the shell inside the container and you can't find your media under `/mnt/sdc2`, you likely didn't map things correctly.

I'm sorry, but that's out of the scope of support for this small application.

**Comment by hacshacdgacs** [comment]
That's fair. That's how I had it set up before and things weren't working for me so clearly it is something on my end screwing it up. Has the deletion side for emby been implemented for if I were to turn off the file-system feature and just have it do that?

**Comment by Schaka** [comment]
Deletion is not implemented for Emby yet.

The exception you're seeing is because you have a redirect set up. 
`http://192.168.68.179:7878/api/v3/movie/616` is being redirected to something else. 

Maybe you're forcing HTTPS - I can't say. 
I'm not willing to turn off streaming mode as of now. It would load unnecessarily large data into RAM. Likely wouldn't cause any issues - but still.

I'm going to close this issue now and will create a new one solely focused on Emby support. You may check back there to see what's been implemented. Once I have tested and confirmed all features, it'll be merged into main.

**Comment by hacshacdgacs** [comment]
Just a follow up on this, I swapped my media to a completely different system and everything works as expected now. Thanks for your patience throughout this and implementing Emby into the project

**Comment by Schaka** [comment]
Thanks for your feedback. Glad it works for you now.
